# Generated by Django 5.2.14 on 2026-05-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('practice_area', models.CharField(max_length=128)),
                ('stage', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В роботі'), ('waiting', 'Очікує відповідь'), ('urgent', 'Терміново'), ('closed', 'Закрита')], default='new', max_length=32)),
                ('priority', models.CharField(default='Звичайний', max_length=64)),
                ('court_or_authority', models.CharField(blank=True, max_length=255)),
                ('authority_type', models.CharField(blank=True, max_length=128)),
                ('authority_address', models.CharField(blank=True, max_length=255)),
                ('authority_contact', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('opened_at', models.DateField(blank=True, null=True)),
                ('deadline_at', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('income_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('finance_comment', models.TextField(blank=True)),
                ('history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(blank=True, max_length=128)),
                ('folder', models.CharField(blank=True, max_length=128)),
                ('file', models.FileField(blank=True, upload_to='case_documents/')),
                ('external_url', models.URLField(blank=True)),
                ('submitted_at', models.DateField(blank=True, null=True)),
                ('response_due_at', models.DateField(blank=True, null=True)),
                ('responsible_name', models.CharField(blank=True, max_length=128)),
                ('comment', models.TextField(blank=True)),
                ('history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
