# Generated by Codex on 2026-05-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0004_mark_existing_demo_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("lawyer", "Адвокат"), ("assistant", "Помічник"), ("accountant", "Бухгалтер"), ("observer", "Спостерігач")], default="observer", max_length=32)),
                ("can_edit", models.BooleanField(default=True)),
                ("is_demo", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="team_members", to="cases.case")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assigned_cases", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="casemember",
            constraint=models.UniqueConstraint(fields=("case", "user"), name="unique_case_member"),
        ),
    ]
