# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_casemember"),
    ]

    operations = [
        migrations.AddField(
            model_name="casedocument",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
