# Generated by Django 5.2.15 on 2026-06-28 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_case_parties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocument',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case'),
        ),
    ]
