# Generated by Django 5.2.14 on 2026-05-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('court', 'Судове засідання'), ('client_meeting', 'Зустріч з клієнтом'), ('consultation', 'Консультація'), ('document', 'Підготовка/подача документа'), ('deadline', 'Крайній строк'), ('waiting', 'Ожидання відповіді'), ('internal', 'Внутрішня задача'), ('other', 'Інше')], max_length=32)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('authority', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recurrence', models.CharField(blank=True, max_length=128)),
                ('reminder_before', models.CharField(blank=True, max_length=64)),
                ('reminder_channels', models.CharField(blank=True, max_length=128)),
                ('reminder_recipients', models.CharField(blank=True, max_length=128)),
                ('reminder_log', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('planned', 'Заплановано'), ('waiting', 'Очікує виконання'), ('done', 'Виконано'), ('moved', 'Перенесено'), ('cancelled', 'Скасовано'), ('overdue', 'Просрочено')], default='planned', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('crm', 'CRM'), ('telegram', 'Telegram'), ('sms', 'SMS'), ('email', 'Email')], max_length=32)),
                ('remind_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(default='pending', max_length=64)),
            ],
        ),
    ]
