# Generated by Django 5.2.14 on 2026-05-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
