# Generated by Django 5.2.14 on 2026-06-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_is_demo_invoice_is_demo_payment_is_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=128)),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='Готово', max_length=64)),
                ('accrued_on', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-accrued_on', '-id'],
            },
        ),
    ]
