# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="module_permissions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
