# Generated by Codex on 2026-05-19

from django.db import migrations, models
from django.utils import timezone


def mark_existing_profiles_active(apps, _schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    UserProfile.objects.filter(last_login_at__isnull=True).update(
        last_login_at=timezone.now(),
        password_temporary=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_module_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_login_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="password_temporary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="password_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_profiles_active, migrations.RunPython.noop),
    ]
