# Generated by Django 5.2.14 on 2026-05-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_password_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
