# Generated by Django 5.2.14 on 2026-06-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_crmsettings_integration_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmsettings',
            name='document_archive_folders',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
