# Generated by Django 5.2.15 on 2026-06-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_crmsettings_document_archive_folders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_label',
            field=models.TextField(blank=True),
        ),
    ]
