# Generated by Django 5.2.15 on 2026-07-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_key', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('content', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI skill',
                'verbose_name_plural': 'AI skills',
            },
        ),
    ]
