# Generated by Django 5.2.15 on 2026-07-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_aiskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiKnowledgeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_key', models.CharField(db_index=True, max_length=64)),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('size_chars', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI knowledge doc',
                'verbose_name_plural': 'AI knowledge docs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='aiskill',
            name='request_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
