# Generated by Django 5.2.15 on 2026-07-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_aiknowledgedoc_aiskill_request_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiCaseAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI case assistant',
                'verbose_name_plural': 'AI case assistants',
                'ordering': ['-created_at'],
            },
        ),
    ]
