# Generated by Django 5.2.15 on 2026-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_aicaseassistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiskill',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
