# Generated by Django 5.2.15 on 2026-07-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_aiskill_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicaseassistant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
