# Generated by Django 5.2.14 on 2026-05-17 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(default='Планова', max_length=64)),
                ('status', models.CharField(choices=[('todo', 'Потрібно зробити'), ('in_progress', 'В роботі'), ('done', 'Виконано'), ('moved', 'Перенесено'), ('overdue', 'Просрочено')], default='todo', max_length=32)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('coexecutors', models.JSONField(blank=True, default=list)),
                ('show_in_calendar', models.BooleanField(default=False)),
                ('planner_manual', models.BooleanField(default=False)),
                ('planner_important', models.BooleanField(default=False)),
                ('planner_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('reminder_before', models.CharField(blank=True, max_length=64)),
                ('reminder_channel', models.CharField(blank=True, max_length=128)),
                ('subtasks', models.JSONField(blank=True, default=list)),
                ('comments', models.JSONField(blank=True, default=list)),
                ('history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='cases.case')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
