# Generated by Django 5.2.14 on 2026-05-17 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('client_type', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('telegram_username', models.CharField(blank=True, max_length=128)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=128)),
                ('telegram_connected', models.BooleanField(default=False)),
                ('photo_url', models.URLField(blank=True)),
                ('show_photo', models.BooleanField(default=False)),
                ('request_summary', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('new', 'Новий'), ('active', 'Активний'), ('regular', 'Постійний клієнт'), ('do_not_contact', 'Не турбувати')], default='new', max_length=32)),
                ('consent_to_marketing', models.BooleanField(default=False)),
                ('risk_level', models.CharField(blank=True, max_length=64)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateField(blank=True, null=True)),
                ('last_contact_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('channel', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_communications', to='cases.case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='clients.client')),
            ],
        ),
    ]
