# Generated by Django 5.2.14 on 2026-05-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='messagedelivery',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
