# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_campaign_is_demo_messagedelivery_is_demo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("channel", models.CharField(default="Telegram", max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_demo", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
    ]
