# Generated by Django 5.2.15 on 2026-06-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_automationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.FileField(blank=True, upload_to='mailing_images/'),
        ),
    ]
